<?php
/**
 * Encryption module contains functions related to encryption and security for this project
 *
 * @author Reishandy (isthisruxury@gmail.com)
 */
require_once "../../src/config/config.php";

/**
 * This function generates a new random bytes for used as an encryption key
 *
 * @return string Randomly generated key in the form of bytes (not actual string)
 * @author Reishandy (isthisruxury@gmail.com)
 */
function generateKey(): string
{
    return openssl_random_pseudo_bytes(PRIMARY_SIZE);
}

/**
 * This function generates a new random bytes for used as iv or salt
 *
 * @return string Randomly generated bytes (not actual string)
 * @author Reishandy (isthisruxury@gmail.com)
 */
function generateSecondaryKey(): string
{
    return openssl_random_pseudo_bytes(SECONDARY_SIZE);
}

/**
 * This function is used to encrypt string with openssl_encrypt and using AES-256 Algorithm
 *
 * @param string $plaintext String to be encrypted
 * @param string $key Key used to encrypt, must be in the form of bytes
 * @param string $iv vector used to encrypt, must be in the form of bytes
 * @return false|string The encrypted plaintext, or false as failure
 * @author Reishandy (isthisruxury@gmail.com)
 */
function encrypt(string $plaintext, string $key, string $iv): false|string
{
    return openssl_encrypt($plaintext, ENCRYPTION_ALGORITHM, $key, 0, $iv);
}

/**
 * This function is used to decrypt an encrypted string with openssl_encrypt and using AES-256 Algorithm
 *
 * @param string $ciphertext String to be decrypted
 * @param string $key Key used to decrypt, must be in the form of bytes
 * @param string $iv Initialization vector used to decrypt, must be in the form of bytes
 * @return false|string The decrypted ciphertext, or false as failure
 * @author Reishandy (isthisruxury@gmail.com)
 */
function decrypt(string $ciphertext, string $key, string $iv): false|string
{
    return openssl_decrypt($ciphertext, ENCRYPTION_ALGORITHM, $key, 0, $iv);
}

/**
 * Used to encrypt AES-key in the form of string bytes with a password string as the key
 *
 * This function will encrypt the inputted key by converting it into base64, the key used for this encryption will be
 * derived from the inputted password string with PBKDF2 and sha3-256. The algorithm used to encrypt is AES-256, and it
 * will return an array containing the encrypted key, salt used to derive the jey from the password, and iv for
 * encryption that is tied to this specific key, all the return values are in the form of base64 string.
 *
 * @param string $key Key to be encrypted, in the form of bytes
 * @param string $password String used as derivative for the key to encryption
 * @return array [0: encrypted key base64, 1: salt base64, 2: iv base64]
 * @author Reishandy (isthisruxury@gmail.com)
 */
function encryptKey(string $key, string $password): array
{
    $keyString = base64_encode($key);

    $salt = generateSecondaryKey();
    $iv = generateSecondaryKey();

    $userKey = hash_pbkdf2(HASH_ALGORITHM, $password, $salt, ITERATION, PRIMARY_SIZE);
    $encryptedKey = openssl_encrypt($keyString, ENCRYPTION_ALGORITHM, $userKey, 0, $iv);


    return [$encryptedKey, base64_encode($salt), base64_encode($iv)];
}

/**
 * Used to decrypt AES-key in the form of encrypted base64
 *
 * This function is intended to decrypt a key that has gone through encryptKey() function, all arguments need to be
 * in the form of base64 except password. This function will first decode the salt and iv, and then it will use the salt
 * to create a key derived from the inputted password using PBKDF2 sha3-256. The salt is necessary for producing the
 * same key derived from the password. Then this function will decrypt the encrypted key with the iv and derived key from
 * password that will result in a base64 encoded bytes, which this function will decode first before being returned.
 *
 * @param string $password String used as derivative for key decryption
 * @param string $encryptedKey Base64 encoded and encrypted key, originally bytes
 * @param string $salt Base64 encoded salt, originally bytes
 * @param string $iv Base64 encoded iv, originally bytes
 * @return false|string Decrypted key in the form of bytes
 * @author Reishandy (isthisruxury@gmail.com)
 */
function decryptKey(string $password, string $encryptedKey, string $salt, string $iv): false|string
{
    $salt = base64_decode($salt);
    $iv = base64_decode($iv);

    $userKey = hash_pbkdf2(HASH_ALGORITHM, $password, $salt, ITERATION, PRIMARY_SIZE);
    $decryptedKey = openssl_decrypt($encryptedKey, ENCRYPTION_ALGORITHM, $userKey, 0, $iv);

    return base64_decode($decryptedKey);
}